version: '3.1'
services:
  redis:
    image: "redis:alpine"
    ports:
      - 6379:6379
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    ports:
      - 9200:9200
      - 9300:9300
  kibana:
    image: docker.elastic.co/kibana/kibana:6.2.4
    ports:
      - 5601:5601
#  netapp-pokemon:
#    build: .
#    depends_on:
#      - redis
#      - elasticsearch
#    ports:
#      - "5000:5000"
#    links:
#      - redis
#      - elasticsearch
#    environment:
#      - REDIS_URL=redis
#      - ELASTIC_URL=elasticsearch
